name: covidoc
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  bloc: ^7.0.0
  http: ^0.13.3
  url_launcher: ^6.0.3
  flutter_bloc: ^7.0.0
  equatable: ^2.0.0
  firebase_core: ^1.1.1
  firebase_auth: ^1.1.4
  cached_network_image: ^3.0.0
  google_sign_in: ^5.0.3
  either_option: ^2.0.1-dev.1
  cloud_firestore: ^2.1.0
  firebase_storage: ^8.0.6
  google_fonts: ^2.1.0
  image_picker: ^0.7.5
  share: ^2.0.1
  shimmer: ^2.0.0
  flutter_svg: ^0.22.0
  flutter_tags: ^1.0.0-nullsafety.1
  photo_view: ^0.11.1
  readmore: ^2.0.0
  carousel_slider: ^4.0.0-nullsafety.0
  flutter_facebook_auth: ^3.3.3+1
  flutter_twitter_login:
    git:
      url: git://github.com/100lvlmaster/flutter_twitter_login.git
  flutter_widget_from_html: ^0.6.1
  shared_preferences: ^2.0.5
  flutter_signin_button: ^2.0.0
  json_annotation: ^4.0.1
  flutter_sound_lite: ^8.1.1
  permission_handler: ^7.1.0
  path_provider: ^2.0.1
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.3
  json_serializable: ^4.1.2
  very_good_analysis: ^2.0.3

flutter:
  uses-material-design: true
  # generate: true

  assets:
    - assets/
    - assets/chat/
    - assets/forum/
    - assets/register/
    - assets/dashboard/
