name: covidoc
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.10.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  bloc: ^6.1.0
  http: ^0.12.2
  url_launcher: ^5.7.10
  flutter_bloc: ^6.1.1
  equatable: ^1.2.6
  firebase_core: ^0.7.0
  firebase_auth: ^0.20.1
  cached_network_image: ^2.3.3
  google_sign_in: ^4.5.1
  either_option: ^1.0.6
  cloud_firestore: ^0.16.0+1
  firebase_storage: "^7.0.0"
  google_fonts: ^1.1.2
  image_picker: ^0.6.7+21
  share: ^0.6.5+4
  shimmer: ^1.1.2
  flutter_svg: ^0.19.1
  flutter_tags: ^0.4.9+1
  photo_view: ^0.10.3
  readmore: ^1.0.1
  carousel_slider: ^3.0.0
  flutter_facebook_auth: ^2.0.2
  flutter_twitter_login: ^1.1.0
  flutter_widget_from_html: ^0.5.2+1
  shared_preferences: ^0.5.12+4
  flutter_signin_button: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.11
  json_serializable: ^3.5.1
  very_good_analysis: ^1.0.0

flutter:
  uses-material-design: true
  # generate: true

  assets:
    - assets/
    - assets/chat/
    - assets/forum/
    - assets/register/
    - assets/dashboard/
